experiment: hyperspectral_extreme_minimal
save_dir: experiments
resume: false
accelerator: 'gpu'
devices: 4  
strategy: 'auto'

model:
  type: minimal_hyperspectral_cm_kan  # Most minimal version
  params:
    in_dims:
      - 31  # 31 hyperspectral channels
    out_dims:
      - 31
    grid_size: 2  # Minimal grid
    spline_order: 1  # Minimal spline
    residual_std: 0.1
    grid_range:
      - -1.0
      - 1.0
    chunk_size: 64  # Process in tiny chunks

data:
  type: cave
  train:
    source: '/app/data/Train/HSI_PER_RGB'
    target: '/app/data/Train/HSI'
  val:
    source: '/app/data/Test/HSI_PER_RGB'
    target: '/app/data/Test/HSI'
  test:
    source: '/app/data/Test/HSI_PER_RGB'
    target: '/app/data/Test/HSI'

pipeline:
  type: supervised
  params:
    lr: 1e-3
    batch_size: 1  # Minimal batch
    val_batch_size: 1
    test_batch_size: 1
    epochs: 10  # Just for testing
    save_freq: 1
    visualize_freq: 5
    optimiser: 'adam'
    weight_decay: 1e-5

# Memory optimization settings
hardware:
  num_workers: 4 
  pin_memory: false
  mixed_precision: false
  gradient_accumulation_steps: 1
